steps:
  # 1. Initialize, run Terraform to setup core infrastructure, and fetch outputs
  #    Using the hello-world container initially to break circular dependency
  - id: 'tf_apply_base'
    name: 'hashicorp/terraform:1.5.0'
    entrypoint: 'sh'
    args: 
      - '-c'
      - |
        echo 'terraform { backend "gcs" {} }' > backend.tf
        terraform init \
          -backend-config="bucket=$${PROJECT_ID}-terraform-remote-backend" \
          -backend-config="prefix=terraform/state"
        terraform apply -auto-approve
        terraform output -json > tf_outputs.json

  # 3. Read TF outputs and Build the Docker image with injected Vite build-args
  - id: 'docker_build'
    name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        export _VITE_FIREBASE_API_KEY=$(cat tf_outputs.json | grep -o '"firebase_api_key": "[^"]*' | cut -d'"' -f4)
        export _VITE_FIREBASE_AUTH_DOMAIN=$(cat tf_outputs.json | grep -o '"firebase_auth_domain": "[^"]*' | cut -d'"' -f4)
        export _VITE_FIREBASE_APP_ID=$(cat tf_outputs.json | grep -o '"firebase_app_id": "[^"]*' | cut -d'"' -f4)
        export _VITE_FIREBASE_MESSAGING_SENDER_ID=$(cat tf_outputs.json | grep -o '"firebase_messaging_sender_id": "[^"]*' | cut -d'"' -f4)
        export _VITE_FIREBASE_PROJECT_ID=${PROJECT_ID}
        export _VITE_FIREBASE_STORAGE_BUCKET=$(cat tf_outputs.json | grep -o '"firebase_storage_bucket": "[^"]*' | cut -d'"' -f4)
        
        # We assume _VITE_GOOGLE_CLIENT_ID is passed as a Cloud Build substitution var from a trigger
        
        docker build \
          --build-arg _VITE_GOOGLE_CLIENT_ID=${_VITE_GOOGLE_CLIENT_ID} \
          --build-arg _VITE_FIREBASE_API_KEY=$${_VITE_FIREBASE_API_KEY} \
          --build-arg _VITE_FIREBASE_AUTH_DOMAIN=$${_VITE_FIREBASE_AUTH_DOMAIN} \
          --build-arg _VITE_FIREBASE_PROJECT_ID=$${_VITE_FIREBASE_PROJECT_ID} \
          --build-arg _VITE_FIREBASE_STORAGE_BUCKET=$${_VITE_FIREBASE_STORAGE_BUCKET} \
          --build-arg _VITE_FIREBASE_MESSAGING_SENDER_ID=$${_VITE_FIREBASE_MESSAGING_SENDER_ID} \
          --build-arg _VITE_FIREBASE_APP_ID=$${_VITE_FIREBASE_APP_ID} \
          -t us-central1-docker.pkg.dev/${PROJECT_ID}/meal-analysis-repo/meal-analysis-app:$SHORT_SHA \
          .

  # 4. Push Image to Artifact Registry
  - id: 'docker_push'
    name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/${PROJECT_ID}/meal-analysis-repo/meal-analysis-app:$SHORT_SHA']

  # 5. Full Terraform Apply (Updates Cloud Run with new Image)
  - id: 'tf_apply_app'
    name: 'hashicorp/terraform:1.5.0'
    entrypoint: 'sh'
    args: 
      - '-c'
      - |
        terraform apply -auto-approve -var="app_image=us-central1-docker.pkg.dev/${PROJECT_ID}/meal-analysis-repo/meal-analysis-app:$SHORT_SHA"

images:
  - 'us-central1-docker.pkg.dev/${PROJECT_ID}/meal-analysis-repo/meal-analysis-app:$SHORT_SHA'
