steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '--build-arg',
      'VITE_GOOGLE_CLIENT_ID=$_GOOGLE_CLIENT_ID',
      '--build-arg',
      'VITE_FIREBASE_CONFIG=$_FIREBASE_CONFIG',
      '-t',
      'gcr.io/$PROJECT_ID/meal-analysis',
      '.'
    ]
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/meal-analysis']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'meal-analysis'
      - '--image'
      - 'gcr.io/$PROJECT_ID/meal-analysis'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--no-allow-unauthenticated'
      - '--set-env-vars'
      - 'REASONING_ENGINE_URL_BASE=$_REASONING_ENGINE_URL_BASE,VITE_GOOGLE_CLIENT_ID=$_GOOGLE_CLIENT_ID,VITE_FIREBASE_CONFIG=$_FIREBASE_CONFIG'
images:
  - 'gcr.io/$PROJECT_ID/meal-analysis'
substitutions:
  _REASONING_ENGINE_URL_BASE: ''
  _GOOGLE_CLIENT_ID: ''
  _FIREBASE_CONFIG: ''
