# Build Stage
FROM node:25.6.1-slim AS build
WORKDIR /app

# Accept build arguments for Vite 
ARG _VITE_GOOGLE_CLIENT_ID 
ARG _VITE_FIREBASE_API_KEY 
ARG _VITE_FIREBASE_AUTH_DOMAIN 
ARG _VITE_FIREBASE_PROJECT_ID 
ARG _VITE_FIREBASE_STORAGE_BUCKET 
ARG _VITE_FIREBASE_MESSAGING_SENDER_ID 
ARG _VITE_FIREBASE_APP_ID 

# Set them as environment variables for the build 
ENV VITE_GOOGLE_CLIENT_ID=$_VITE_GOOGLE_CLIENT_ID 
ENV VITE_FIREBASE_API_KEY=$_VITE_FIREBASE_API_KEY 
ENV VITE_FIREBASE_AUTH_DOMAIN=$_VITE_FIREBASE_AUTH_DOMAIN 
ENV VITE_FIREBASE_PROJECT_ID=$_VITE_FIREBASE_PROJECT_ID 
ENV VITE_FIREBASE_STORAGE_BUCKET=$_VITE_FIREBASE_STORAGE_BUCKET 
ENV VITE_FIREBASE_MESSAGING_SENDER_ID=$_VITE_FIREBASE_MESSAGING_SENDER_ID 
ENV VITE_FIREBASE_APP_ID=$_VITE_FIREBASE_APP_ID 

COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Production Stage: Node API + Static Files
FROM node:25.6.1-slim
WORKDIR /app

# Accept build arguments for Vite 
ARG _VITE_GOOGLE_CLIENT_ID 
ARG _VITE_FIREBASE_API_KEY 
ARG _VITE_FIREBASE_AUTH_DOMAIN 
ARG _VITE_FIREBASE_PROJECT_ID 
ARG _VITE_FIREBASE_STORAGE_BUCKET 
ARG _VITE_FIREBASE_MESSAGING_SENDER_ID 
ARG _VITE_FIREBASE_APP_ID 

# Set them as environment variables for the build 
ENV VITE_GOOGLE_CLIENT_ID=$_VITE_GOOGLE_CLIENT_ID 
ENV VITE_FIREBASE_API_KEY=$_VITE_FIREBASE_API_KEY 
ENV VITE_FIREBASE_AUTH_DOMAIN=$_VITE_FIREBASE_AUTH_DOMAIN 
ENV VITE_FIREBASE_PROJECT_ID=$_VITE_FIREBASE_PROJECT_ID 
ENV VITE_FIREBASE_STORAGE_BUCKET=$_VITE_FIREBASE_STORAGE_BUCKET 
ENV VITE_FIREBASE_MESSAGING_SENDER_ID=$_VITE_FIREBASE_MESSAGING_SENDER_ID 
ENV VITE_FIREBASE_APP_ID=$_VITE_FIREBASE_APP_ID 

COPY package*.json ./
RUN npm install --omit=dev  
COPY server.js ./
COPY --from=build /app/dist ./dist

# EXPOSE port
ENV PORT=8080
EXPOSE 8080

CMD ["node", "server.js"]
